/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

 #include <stdint.h>
 #include "stm32f303xc.h"
 #include "serial.h"

 #if !defined(__SOFT_FP__) && defined(__ARM_FP)
   #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
 #endif

 #define ALTFUNCTION 0xA00
 #define RXTX 0x770000
 #define HIGHSPEED 0xF00
 #define BAUDRATE 0x46
 #define LED_OUTPUT 0x5555

 void enableLEDs();

 int main(void)
 {
     uint8_t *string_to_send = "Sally is a beautiful dog!\r\n";
     SerialInitialise(BAUD_115200, &USART1_PORT, '$',&processBuffer);
     USART1RX_enableInterrupts();
     enableLEDs();

     // Loop forever
     for(;;)
     {
    	 // Transmit string_to_send via USART1
         SerialOutputString(string_to_send, &USART1_PORT);
     }
 }

 // Function to process buffer contents - always processes the inactive buffer
 void processBuffer(unsigned char* buffer, int size)
 {
     // This function processes the inactive buffer while the other buffer is collecting data
     // Currently just a placeholder - you can implement your specific logic here


     /*
      * Example of what you might want to do with the buffer:
      *
      * - Parse commands
      * - Convert ASCII to values
      * - Forward to another device
      * - Store in non-volatile memory
      * - Perform calculations based on buffer contents
      */


     // For demonstration purposes, send a message indicating buffer processing
     USART1_SendString("Processing inactive buffer...");


     // Here you would actually process the buffer contents
     // This processing happens while the other buffer is now active and collecting data
 }

 void enableLEDs()
 {
     // Enable clock for Port E (LEDs)
     RCC->AHBENR |= RCC_AHBENR_GPIOEEN;

     // Get the most significant 16 bits of port mode register as that is where the mode for the LEDs are defined
     uint16_t* portMode = ((uint16_t*)&(GPIOE->MODER))+1;

     // Set the mode of the port pins to output since they are LEDs
     *portMode = LED_OUTPUT;
 }

